FROM python:3.7.3

COPY ./requirements.txt /requirements.txt
RUN pip install -r /requirements.txt

COPY ./ /
WORKDIR /


EXPOSE 8002

RUN ./manage.py migrate

CMD python manage.py runserver 0.0.0.0:8002 --noreload
